services:
  technitium:
    container_name: technitium
    hostname: technitium
    image: docker.io/technitium/dns-server:15.4.0
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - DNS_SERVER_DOMAIN=MY.DOMAIN.NET
      - DNS_SERVER_ADMIN_PASSWORD=${TECHNITIUM_ADMIN_PASSWORD}
      - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=true
      - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks
      - DNS_SERVER_ENABLE_BLOCKING=true
      - DNS_SERVER_FORWARDERS=9.9.9.9, 149.112.112.112
      - DNS_SERVER_FORWARDER_PROTOCOL=Udp
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
      - DNS_SERVER_LOG_FOLDER_PATH=/var/log/technitium/dns
    networks:
      npm:
    volumes:
      - technitium_config:/etc/dns
      - technitium_logs:/var/log/technitium/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

volumes:
  technitium_config:
    driver: local
  technitium_logs:
    driver: local

# Uncomment this section if using a reverse proxy.
# networks:
#   default:
#     external: true
#     name: npm
