services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/agent:latest
    container_name: arcane-agent
    ports:
      - '3553:3553'
    environment:
      - AGENT_MODE=true
      - EDGE_TRANSPORT=poll
      - AGENT_TOKEN=<TOKEN>
      - MANAGER_API_URL=https://arcane.MY.DOMAIN.COM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
